# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('image_page', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('image_license', models.CharField(blank=True, max_length=100, null=True)),
                ('license_text', models.CharField(max_length=1000)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=100, null=True)),
                ('redownload_flag', models.BooleanField()),
            ],
            options={
                'managed': False,
                'ordering': ('aircraft',),
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'aircraft_type',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type_id', models.IntegerField()),
                ('aircraft_type', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'ordering': ('aircraft_type_id',),
                'db_table': 'types',
            },
        ),
    ]
