# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('image_page', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('image_license', models.CharField(max_length=100)),
                ('license_text', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('aircraft', models.CharField(max_length=100)),
                ('redownload_flag', models.BooleanField()),
            ],
            options={
                'ordering': ('aircraft',),
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('aircraft_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('type_id',),
                'db_table': 'types',
            },
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='aircraft_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlaneViewer.Types'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PlaneViewer.AircraftType'),
        ),
    ]
